import { makeStyles, tokens } from "@fluentui/react-components";

/** List SharePoint: toolbar trên canvas, bảng trong card bóng nhẹ. */
export const useFileManagerStyles = makeStyles({
  root: {
    display: "flex",
    flexDirection: "column",
    height: "100%",
    minHeight: "0",
    backgroundColor: tokens.colorNeutralBackground1,
    fontFamily: tokens.fontFamilyBase,
    paddingLeft: "16px",
    paddingRight: "16px",
    paddingBottom: "16px",
  },
  commandBar: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: "16px",
    minHeight: "56px",
    paddingTop: "8px",
    paddingBottom: "12px",
    flexShrink: 0,
  },
  commandActions: {
    display: "flex",
    alignItems: "center",
    gap: "2px",
    flexShrink: 0,
    padding: "2px",
    borderRadius: tokens.borderRadiusCircular,
    backgroundColor: tokens.colorNeutralBackground3,
  },
  /** Nút icon toolbar: cùng cỡ, nét Regular mặc định. */
  commandIconButton: {
    minWidth: "32px",
    width: "32px",
    height: "32px",
    maxWidth: "32px",
    color: tokens.colorNeutralForeground2,
  },
  listCard: {
    flex: 1,
    minHeight: "0",
    display: "flex",
    flexDirection: "column",
    backgroundColor: tokens.colorNeutralBackground1,
    border: `1px solid ${tokens.colorNeutralStroke2}`,
    borderRadius: tokens.borderRadiusLarge,
    boxShadow: tokens.shadow4,
    overflow: "hidden",
  },
  listPane: {
    flex: 1,
    minHeight: "0",
    overflow: "auto",
  },
  table: {
    width: "100%",
    minWidth: "720px",
    borderCollapse: "separate",
    borderSpacing: "0",
    tableLayout: "fixed",
  },
  headerRow: {
    ":hover": {
      backgroundColor: "transparent",
    },
  },
  headerCell: {
    position: "sticky",
    top: "0",
    zIndex: 1,
    height: "48px",
    paddingTop: "0",
    paddingBottom: "0",
    paddingLeft: "4px",
    paddingRight: "4px",
    backgroundColor: tokens.colorNeutralBackground1,
    borderBottom: `1px solid ${tokens.colorNeutralStroke2}`,
    textAlign: "left",
    verticalAlign: "middle",
  },
  headerTitle: {
    display: "block",
    paddingLeft: "8px",
    paddingRight: "8px",
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
    color: tokens.colorNeutralForeground1,
    fontSize: tokens.fontSizeBase300,
    fontWeight: tokens.fontWeightBold,
    lineHeight: tokens.lineHeightBase300,
  },
  row: {
    cursor: "default",
    ":hover": {
      backgroundColor: tokens.colorNeutralBackground1Hover,
    },
  },
  rowFolder: {
    cursor: "pointer",
  },
  cell: {
    height: "42px",
    paddingTop: "0",
    paddingBottom: "0",
    paddingLeft: "12px",
    paddingRight: "12px",
    verticalAlign: "middle",
    fontSize: tokens.fontSizeBase300,
    lineHeight: tokens.lineHeightBase300,
    color: tokens.colorNeutralForeground2,
    whiteSpace: "nowrap",
    overflow: "hidden",
    textOverflow: "ellipsis",
  },
  nameCell: {
    width: "36%",
    minWidth: "240px",
    color: tokens.colorNeutralForeground1,
  },
  modifiedCell: {
    width: "148px",
  },
  extraCell: {
    width: "168px",
  },
  sizeCell: {
    width: "112px",
  },
  nameInner: {
    display: "flex",
    alignItems: "center",
    gap: "12px",
    minWidth: "0",
  },
  nameText: {
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
    color: tokens.colorNeutralForeground1,
    fontWeight: tokens.fontWeightRegular,
    fontSize: tokens.fontSizeBase300,
  },
  nameFolder: {
    ":hover": {
      color: tokens.colorBrandForeground1,
      textDecorationLine: "underline",
    },
  },
  personPill: {
    display: "inline-block",
    maxWidth: "100%",
    overflow: "hidden",
    textOverflow: "ellipsis",
    verticalAlign: "middle",
    paddingTop: "3px",
    paddingBottom: "3px",
    paddingLeft: "8px",
    paddingRight: "8px",
    borderRadius: "2px",
    backgroundColor: tokens.colorNeutralBackground3,
    color: tokens.colorNeutralForeground1,
    fontSize: tokens.fontSizeBase200,
    lineHeight: tokens.lineHeightBase200,
  },
  loadMore: {
    display: "flex",
    justifyContent: "flex-start",
    padding: "8px 12px 16px",
  },
  pickerSurface: {
    minWidth: "280px",
    maxHeight: "360px",
    overflowY: "auto",
    paddingTop: "8px",
    paddingBottom: "8px",
  },
});
