import { makeStyles, tokens } from "@fluentui/react-components";

/** List: toolbar pill nét mảnh, bảng trong card viền nhẹ. */
export const useFileManagerStyles = makeStyles({
  root: {
    display: "flex",
    flexDirection: "column",
    height: "100%",
    minHeight: "0",
    backgroundColor: tokens.colorNeutralBackground1,
    fontFamily: tokens.fontFamilyBase,
    paddingLeft: "16px",
    paddingRight: "16px",
    paddingBottom: "16px",
  },
  commandBar: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: "16px",
    minHeight: "56px",
    paddingTop: "8px",
    paddingBottom: "12px",
    flexShrink: 0,
  },
  commandBarStart: {
    display: "flex",
    alignItems: "center",
    gap: "2px",
    minWidth: "0",
    flex: 1,
  },
  /** Đổi chế độ browse / có quyền xem — pill icon trước breadcrumb. */
  viewSwitch: {
    display: "flex",
    alignItems: "center",
    gap: "4px",
    flexShrink: 0,
    paddingTop: "4px",
    paddingBottom: "4px",
    paddingLeft: "6px",
    paddingRight: "6px",
    borderRadius: tokens.borderRadiusCircular,
    backgroundColor: tokens.colorNeutralBackground3,
  },
  commandActions: {
    display: "flex",
    alignItems: "center",
    gap: "4px",
    flexShrink: 0,
    paddingTop: "4px",
    paddingBottom: "4px",
    paddingLeft: "10px",
    paddingRight: "10px",
    borderRadius: tokens.borderRadiusCircular,
    backgroundColor: tokens.colorNeutralBackground3,
  },
  /** Nút icon toolbar: cùng cỡ, nét Regular mặc định. */
  commandIconButton: {
    minWidth: "32px",
    width: "32px",
    height: "32px",
    maxWidth: "32px",
    color: tokens.colorNeutralForeground2,
  },
  commandIconButtonActive: {
    color: tokens.colorNeutralForeground1,
    backgroundColor: tokens.colorNeutralBackground1,
  },
  listCard: {
    flex: 1,
    minHeight: "0",
    display: "flex",
    flexDirection: "column",
    backgroundColor: tokens.colorNeutralBackground1,
    border: `${tokens.strokeWidthThin} solid ${tokens.colorNeutralStroke3}`,
    borderRadius: tokens.borderRadiusLarge,
    overflow: "hidden",
  },
  listPane: {
    flex: 1,
    minHeight: "0",
    overflow: "auto",
  },
  /** Đo bề rộng khả dụng; bảng full ngang khi hẹp hơn viewport, rộng hơn → listPane cuộn ngang. */
  tableViewport: {
    width: "100%",
    minWidth: "0",
  },
  table: {
    borderCollapse: "separate",
    borderSpacing: "0",
    tableLayout: "fixed",
  },
  headerRow: {
    ":hover": {
      backgroundColor: "transparent",
    },
  },
  headerCell: {
    position: "sticky",
    top: "0",
    zIndex: 1,
    height: "48px",
    paddingTop: "0",
    paddingBottom: "0",
    paddingLeft: "4px",
    paddingRight: "12px",
    backgroundColor: tokens.colorNeutralBackground1,
    borderBottom: `${tokens.strokeWidthThin} solid ${tokens.colorNeutralStroke3}`,
    textAlign: "left",
    verticalAlign: "middle",
    overflow: "visible",
    cursor: "grab",
    userSelect: "none",
    ":active": {
      cursor: "grabbing",
    },
  },
  headerCellDropBefore: {
    boxShadow: `inset 2px 0 0 ${tokens.colorBrandStroke1}`,
  },
  headerCellDropAfter: {
    boxShadow: `inset -2px 0 0 ${tokens.colorBrandStroke1}`,
  },
  /** Gạch ngắn (cách mép trên/dưới); chỉ hiện khi hover/kéo đúng tay cầm đó. */
  columnResizeHandle: {
    position: "absolute",
    top: "0",
    right: "0",
    zIndex: 2,
    width: "8px",
    height: "100%",
    padding: "0",
    border: "none",
    backgroundColor: "transparent",
    cursor: "col-resize",
    "::after": {
      content: '""',
      position: "absolute",
      top: "10px",
      bottom: "10px",
      left: "3px",
      width: "1px",
      opacity: 0,
      backgroundColor: tokens.colorNeutralStroke2,
    },
    ":hover::after": {
      opacity: 1,
      backgroundColor: tokens.colorBrandForeground1,
    },
    ":hover": {
      backgroundColor: "transparent",
    },
  },
  columnResizeHandleActive: {
    "::after": {
      opacity: 1,
      backgroundColor: tokens.colorBrandForeground1,
    },
  },
  headerTitle: {
    display: "block",
    minWidth: "0",
    paddingLeft: "8px",
    paddingRight: "4px",
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
    color: tokens.colorNeutralForeground1,
    fontSize: tokens.fontSizeBase300,
    fontWeight: tokens.fontWeightBold,
    lineHeight: tokens.lineHeightBase300,
  },
  headerMenuButton: {
    display: "inline-flex",
    alignItems: "center",
    maxWidth: "100%",
    height: "100%",
    margin: "0",
    padding: "0",
    border: "none",
    backgroundColor: "transparent",
    cursor: "pointer",
    color: "inherit",
    font: "inherit",
    textAlign: "left",
  },
  headerChevron: {
    flexShrink: 0,
    color: tokens.colorNeutralForeground3,
  },
  headerMenuButtonSorted: {
    color: tokens.colorNeutralForeground1,
  },
  headerSortGlyph: {
    flexShrink: 0,
    color: tokens.colorBrandForeground1,
  },
  row: {
    cursor: "default",
    ":hover": {
      backgroundColor: tokens.colorNeutralBackground1Hover,
    },
  },
  rowFolder: {
    cursor: "pointer",
  },
  cell: {
    height: "48px",
    paddingTop: "0",
    paddingBottom: "0",
    paddingLeft: "12px",
    paddingRight: "12px",
    verticalAlign: "middle",
    fontSize: tokens.fontSizeBase300,
    lineHeight: tokens.lineHeightBase300,
    color: tokens.colorNeutralForeground2,
    whiteSpace: "nowrap",
    overflow: "hidden",
    textOverflow: "ellipsis",
  },
  nameCell: {
    color: tokens.colorNeutralForeground1,
  },
  modifiedCell: {
    minWidth: "0",
  },
  extraCell: {
    minWidth: "0",
  },
  sizeCell: {
    minWidth: "0",
  },
  nameInner: {
    display: "flex",
    alignItems: "center",
    gap: "12px",
    minWidth: "0",
  },
  nameText: {
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
    color: tokens.colorNeutralForeground1,
    fontWeight: tokens.fontWeightRegular,
    fontSize: tokens.fontSizeBase300,
  },
  nameFolder: {
    ":hover": {
      color: tokens.colorBrandForeground1,
      textDecorationLine: "underline",
    },
  },
  personPill: {
    display: "inline-block",
    maxWidth: "100%",
    overflow: "hidden",
    textOverflow: "ellipsis",
    verticalAlign: "middle",
    paddingTop: "3px",
    paddingBottom: "3px",
    paddingLeft: "8px",
    paddingRight: "8px",
    borderRadius: tokens.borderRadiusCircular,
    backgroundColor: tokens.colorNeutralBackground3,
    color: tokens.colorNeutralForeground1,
    fontSize: tokens.fontSizeBase200,
    lineHeight: tokens.lineHeightBase200,
  },
  loadMore: {
    display: "flex",
    flexDirection: "column",
    alignItems: "flex-start",
    padding: "8px 12px 16px",
  },
  loadMoreSentinel: {
    height: "1px",
    width: "100%",
  },
  loadMoreButton: {
    borderRadius: tokens.borderRadiusCircular,
    color: tokens.colorNeutralForeground2,
  },
  emptyState: {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "center",
    gap: "8px",
    paddingTop: "72px",
    paddingBottom: "72px",
    paddingLeft: "24px",
    paddingRight: "24px",
    textAlign: "center",
  },
  emptyIcon: {
    fontSize: "48px",
    color: tokens.colorNeutralForeground4,
  },
  emptyHint: {
    color: tokens.colorNeutralForeground3,
    maxWidth: "360px",
  },
  errorBanner: {
    marginTop: "0",
    marginBottom: "12px",
    marginLeft: "0",
    marginRight: "0",
    borderRadius: tokens.borderRadiusCircular,
    backgroundColor: tokens.colorNeutralBackground3,
  },
  errorRetry: {
    marginLeft: "8px",
    borderRadius: tokens.borderRadiusCircular,
  },
  pickerSurface: {
    minWidth: "260px",
    maxWidth: "320px",
    padding: "0",
    border: `${tokens.strokeWidthThin} solid ${tokens.colorNeutralStroke3}`,
    borderRadius: tokens.borderRadiusLarge,
    boxShadow: tokens.shadow8,
    overflow: "hidden",
  },
  pickerHeader: {
    display: "block",
    paddingTop: "12px",
    paddingBottom: "8px",
    paddingLeft: "16px",
    paddingRight: "16px",
    color: tokens.colorNeutralForeground1,
    fontSize: tokens.fontSizeBase300,
    fontWeight: tokens.fontWeightSemibold,
    lineHeight: tokens.lineHeightBase300,
  },
  pickerList: {
    maxHeight: "280px",
    overflowY: "auto",
    paddingBottom: "8px",
    scrollbarWidth: "thin",
    scrollbarColor: `${tokens.colorNeutralStroke1} transparent`,
    "::-webkit-scrollbar": {
      width: "6px",
    },
    "::-webkit-scrollbar-thumb": {
      backgroundColor: tokens.colorNeutralStroke1,
      borderRadius: tokens.borderRadiusCircular,
    },
  },
  pickerSectionLabel: {
    display: "block",
    paddingTop: "4px",
    paddingBottom: "4px",
    paddingLeft: "16px",
    paddingRight: "16px",
    color: tokens.colorNeutralForeground3,
    fontSize: tokens.fontSizeBase200,
    fontWeight: tokens.fontWeightSemibold,
    lineHeight: tokens.lineHeightBase200,
  },
  pickerLockedRow: {
    display: "flex",
    alignItems: "center",
    gap: "10px",
    minHeight: "36px",
    paddingLeft: "16px",
    paddingRight: "16px",
    color: tokens.colorNeutralForeground2,
    fontSize: tokens.fontSizeBase300,
    lineHeight: tokens.lineHeightBase300,
  },
  pickerLockedIcon: {
    flexShrink: 0,
    fontSize: "16px",
    color: tokens.colorNeutralForeground3,
  },
  pickerCheckboxLabel: {
    display: "flex",
    alignItems: "center",
    flex: "1",
    minWidth: "0",
    minHeight: "36px",
    marginTop: "0",
    marginBottom: "0",
    paddingTop: "0",
    paddingBottom: "0",
    paddingLeft: "8px",
    paddingRight: "8px",
    backgroundColor: "transparent",
    backgroundImage: "none",
    boxShadow: "none",
  },
  pickerCheckboxIndicator: {
    alignSelf: "center",
    marginTop: "0",
    marginBottom: "0",
    marginLeft: "8px",
    marginRight: "8px",
  },
  pickerCheckbox: {
    display: "flex",
    alignItems: "center",
    minHeight: "36px",
    width: "100%",
    maxWidth: "100%",
    boxSizing: "border-box",
    color: tokens.colorNeutralForeground1,
    backgroundColor: "transparent",
    backgroundImage: "none",
    boxShadow: "none",
    ":hover": {
      backgroundColor: tokens.colorNeutralBackground1Hover,
    },
  },
});
